export const HOME_FETCH_MEETUP_LIST_BEGIN = 'HOME_FETCH_MEETUP_LIST_BEGIN';
export const HOME_FETCH_MEETUP_LIST_SUCCESS = 'HOME_FETCH_MEETUP_LIST_SUCCESS';
export const HOME_FETCH_MEETUP_LIST_FAILURE = 'HOME_FETCH_MEETUP_LIST_FAILURE';
export const HOME_FETCH_MEETUP_LIST_DISMISS_ERROR = 'HOME_FETCH_MEETUP_LIST_DISMISS_ERROR';
export const HOME_CHANGE_LOCATION = 'HOME_CHANGE_LOCATION';
export const HOME_EMPTY_MEETUP_LIST = 'HOME_EMPTY_MEETUP_LIST';
export const HOME_LOCATION_KEY_DOWN = 'HOME_LOCATION_KEY_DOWN';
export const HOME_CHANGE_RADIUS = 'HOME_CHANGE_RADIUS';
